---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  labels:
    name: minio-secrets
    app: minio
  namespace: minio-namespace
type: Opaque
data:
  MINIO_ROOT_USER : <user>
  MINIO_ROOT_PASSWORD: <password_length_more_than_10>
