version: "3.9"
name: task-two
services:
  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - myvol:/var/lib/mysql
    networks:
      - mynet

  myapp:
    image: stackupiss/northwind-app:v1
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "mydb"
      DB_USER: "root"
      DB_PASS: "changeit"
    networks:
      - mynet

volumes:
  myvol:

networks:
  mynet:
    driver: bridge