---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  namespace: myns
data:
  hosts: |
    127.0.0.1	localhost
    255.255.255.255	broadcasthost
    ::1             localhost
    # End of section
