---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: myns
spec:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # get from running kubectl get sc
  storageClassName: do-block-storage-xfs
  
  
