---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deployment
  labels:
    name: dov-bear-deployment
  namespace: myns
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dov-bear-pod
      dept: dev
  template:
    metadata:
      name: dov-bear-pod
      labels:
        name: dov-bear-pod
        dept: dev
    spec:
      containers:
        - name: dov-bear-container
          image: cyonglun/dov-bear@sha256:fe15bf9c007baac8b1213463b07b34835135062e48562191dd83149c374a089b
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: INSTANCE_NAME
              value: "dov-bear"
            - name: PORT
              value: "3000"
            - name: INSTANCE_HASH
              # value: "dov-bear-12345"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            ## Docker image might not have curl installed
            # exec:
            #   command:
            #   - "/bin/sh"
            #   - "-c"
            #   - "curl http://localhost:$PORT/healthz || exit 1"

---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
  labels:
    name: dov-bear-svc
  namespace: myns
spec:
  type: ClusterIP
  selector:
    name: dov-bear-pod
    dept: dev
  ports:
    - port: 3000
      targetPort: 3000
