---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  labels:
    app: codeserver
    name: cs-pvc
  namespace: cs-ns
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-xfs
