---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-deploy
  labels:
    app: codeserver
    name: oauth2-deploy
  namespace: cs-ns
spec:
  selector:
    matchLabels:
      app: codeserver
      name: oauth2-pod
  template:
    metadata:
      name: oauth2-pod
      labels:
        app: codeserver
        name: oauth2-pod
    spec:
      containers:
      - name: oauth2-container
        image: bitnami/oauth2-proxy:7.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4180
        args:
          - --provider=github
          - --email-domain=* 
          - --upstream=file:///dev/null
          - --http-address=0.0.0.0:4180
        envFrom:
          - secretRef:
              name: oauth2-secret

---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-svc
  labels:
    app: codeserver
    name: oauth2-svc
  namespace: cs-ns
spec:
  type: ClusterIP
  selector:
    name: oauth2-pod
  ports:
  - port: 4180
    targetPort: 4180

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-ingress
  labels:
    app: codeserver
    name: oauth2-ingress
  namespace: cs-ns
spec:
  ingressClassName: nginx
  rules:
  - host: cs-146.190.7.68.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/oauth2"
        backend:
          service:
            name: oauth2-svc
            port: 
              number: 4180
