---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deployment
  labels:
    name: bggapp-deployment
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapp-pod
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
            - name: BGG_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bggapp-config
                  key: DB_HOST
            - name: BGG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: bggapp-secret
                  key: DB_USER
            - name: BGG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bggapp-secret
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
  namespace: bggns
spec:
  # type: ClusterIP
  # type: NodePort
  type: LoadBalancer
  selector:
    name: bggapp-pod
  ports:
    - port: 80
      targetPort: 3000
