---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    name: myns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deployment
  labels:
    name: dov-bear-deployment
  namespace: myns
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dov-bear-pod
      dept: dev
  template:
    metadata:
      name: dov-bear-pod
      labels:
        name: dov-bear-pod
        dept: dev
        deny-all: "true"
        allow-dns: "true"
    spec:
      containers:
        - name: dov-bear-container
          image: cyonglun/dov-bear@sha256:fe15bf9c007baac8b1213463b07b34835135062e48562191dd83149c374a089b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: INSTANCE_NAME
              value: "dov-bear"
            - name: PORT
              value: "3000"
            - name: INSTANCE_HASH
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "32Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
  labels:
    name: dov-bear-svc
  namespace: myns
spec:
  type: ClusterIP
  selector:
    name: dov-bear-pod
    dept: dev
  ports:
    - port: 3000
      targetPort: 3000
      
---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-hsvc
  labels:
    name: dov-bear-hsvc
  namespace: myns
spec:
  clusterIP: None
  selector:
    name: dov-bear-pod
    dept: dev
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dov-bear-hpa
  labels: 
    name: dov-bear-hpa
  namespace: myns
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dov-bear-deployment
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: myns
spec:
  podSelector:
    matchLabels:
      deny-all: "true"
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: myns
spec:
  podSelector:
    matchLabels:
      allow-dns: "true"
  policyTypes:
    - Egress
  egress:
  - to: 
    - ports:
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
